name: legal_argument_reasoning_task_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
    - datasets==2.14.6
    - pymupdf
    - nltk==3.7
    - numpy==1.22.2
    - pandas==1.4.2
    - scikit_learn==1.3.2
    - sentence_transformers==2.2.2
    - transformers==4.20.1
